http:
  routers:
    https_redirect:
      entrypoints: 
        - "http"
      middlewares: 
        - "https-redirect"
      service: "noop" 
      rule: "HostRegexp(`{host:[a-z-.]+}`)"
      
    gkoerk:
      entrypoints: 
        - "https"
      middlewares:
        - "forward-auth"
      service: "noop"
      rule: "Host(`gkoerk.com`)"      
        tls:
          certResolver: "namecheap"
          domains:
          - main: "*.gkoerk.com"
            sans: "gkoerk.com"  
 	  
    qnapunofficial:
      entrypoints: 
      - "https"    
      middlewares: 
      - "forward-auth"
      service: "noop"
      rule: "Host(`qnapunofficial.com`)"
      tls:
        certResolver: "namecheap"
        domains:
        - main: "*.qnapunofficial.com"
          sans: "qnapunofficial.com" 

    oracleoptimizer:
      entrypoints: 
      - "https"    
      middlewares:
      - "forward-auth"
      service: "noop"
      rule: "Host(`oracleoptimizer.com`)" 	    
        tls:
          certResolver: "namecheap"
          domains:
 	  - main: "*.oracleoptimizer.com"
 	    sans: "oracleoptimizer.com" 

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: "https"
    compress:
      compress:
    forward-auth:
      forwardAuth:
        address: "http://192.168.1.100:8080/authorize"
        authResponseHeaders:
          - "X-FORWARDAUTH-NAME"
          - "X-FORWARDAUTH-SUB"
          - "X-FORWARDAUTH-EMAIL"
    basic-user:
      basicAuth:
        users:
          - "admin:<bcrypt password from htpasswd command>"	  
    secured:
      chain:
        middlewares:
          - "https-redirect"
          - "forward-auth"

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
