global:
  checkNewVersion = true

serversTransport:
  insecureSkipVerify = true
	
entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      trustedIPs: 
        - "172.0.0.1/8"
        - "10.0.0.1/8"	
  https:
    address: ":443"

providers:
  docker:	
    endpoint: "unix:///var/run/docker.sock"	
    watch: true
    swarmMode: true
    network: "traefik_public"
    defaultRule: "Host(`{{ .Name }}.gkoerk.com`)"
    useBindPortIP: false
    exposedByDefault: false

  file:
    filename: "/etc/traefik/dynamic-conf.toml"
    watch: true

api:
  dashboard: true
  insecure: true
  
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: "metrics"

ping:
  entryPoint: "ping"

log:
  level: "ERROR"
  filePath: "/etc/traefik/traefik.log"

#[accessLog]
#  filePath = "/etc/traefik/access.log"
#  bufferingSize = 100

certificatesResolvers:
  namecheap:
    acme:
      email: "gkoerk@gmail.com"
      storage: "/etc/traefik/acme.json"
#       caserver: https://acme-staging-v02.api.letsencrypt.org/directory"    
      dnsChallenge:
        provider: "namecheap"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
	delayBeforeCheck: 0
